### ISSUE TITLE
Logowanie za pomoca adresu email

### ISSUE THREAD

**Issue by ptrstpp950** [dotnetomaniak/dotnetomaniak#10]
Część użytkowników nie pamięta swojej nazwy użytkownika. Byłoy wygodne umożliwić logowanie za pomocą adresu email, albo jakaś formę przypomnienia nazwy użytkownika.

**Comment by pawlos** [comment]
Ewentualny inne sposób odzyskania loginu to reset hasła. W mailu przychodzi login + hasło. 

Może to powinno być do zmiany, aby hasło była ustawiane na stronie a nie automatycznie generowane i wysyłane na maila?

**Comment by kamil-mrzyglod** [comment]
@ptrstpp950 a rozważałeś integrację z jakimkolwiek providerem tożsamości typu Azure B2C albo Auth0?

**Comment by ar-tour** [comment]
Zdecydowanie byłbym za oddelegowaniem uwierzytelniania do zewnętrznych provider'ów. Mogę się tym zająć, ale proponuję poczekać z tym na migrację do .net core.
@ptrstpp950 co myślisz?

**Comment by ptrstpp950** [comment]
Migracja na zewnętrzynch prowiderów jest niestety trudna i czasochłonna. Bo trzeba przez pewien czas utrzymywać podwójne logowanie, tak by migrować hasła użytkownikom. Dlatego na razie tego nie rozważałem. 
Dodatkowo można dodawać dowolnego providera OpenId, wystarczy wypełnić odpowiedenie pola, więc każdy kto chce może z tego skorzystać. 
I jeszcze jedna kwestia. Taka migracja to koszty deweloperskie oraz koszty późniejsze za logowania użytkowników. Trzeba by więc policzyć ile by to mnie kosztowało i na jakich zasadach.

Co Wy na to?

**Comment by kamil-mrzyglod** [comment]
W przypadku Azure B2C koszt jest do pewnego czasu darmowy(jeśli dobrze pamiętam - z 50k uwierzytelnień) pod warunkiem, że masz subskrypcję "otwartą", tj. nie płacisz z góry.

W tym wypadku lepiej wygląda Auth0, gdzie Free masz 7000 aktywnych użytkowników bez limitu logowań. 

Migracja może być faktycznie czasochłonna - wszystko zalezy od tego jak obecnie to wygląda i jakie są możliwości na automatyzację. Teoretycznie do tematu mozna podejść tak, że w momencie przepięcia idzie info, że trzeba będzie ustawić nowe hasło - używając już nowego dostawcy. 

Ilu jest obecnie aktywnych użytkowników na stronie?

**Comment by ptrstpp950** [comment]
Logujących się około 150. Taki mail zawsze powoduje utratę użytkowników, bo się nie chce, więc lepszym rozwiązaniem jest przepięcie "powolne" i gdy stwierdzisz że migracja jest już zakończona, to na koniec wysyłasz maila.
Doświadczenie zawodowe mówi mi, nigdy nie wysyłaj użytkownikom maila że wymagana jest zmiana hasła, bo to może oznaczać dla nich probę przejęcia konta.

**Comment by kamil-mrzyglod** [comment]
To przy 150 to już kwestia za/przeciw za konkretnym providerem. Musiałbym spojrzeć w kod by zobaczyć jak wygląda logika uwierzytelniania/autoryzacji, ale jeśli i tak jest kwestia by przechodzić na .NET Core, trudność jest raczej w odpowiednim middleware, który obsłuży legacy uwierzytelnianie i nowego dostawcę niż w samym procesie przepięcia ;)

**Comment by ptrstpp950** [comment]
Przy Azure B2C to wcale tak różowo nie wygląda. Pomimmo że liczba mała:
150 uzytkowników * 30 dni * 2 uwierzytelaniania dziennie => 9000.
Potem tylko modlitwa by portal nie rósł, bo jak ludzie będą wchodzić więcej razy niż 2 to maskara gotowa w kosztach. Auth0 wygląda licencyjnie lepiej, ale muszę poczytać.

Masz oczywiście rację że dużym problemem będzie middleware. Proponuję zrobić tak:

1. Dodanie przypominania maila to drobiazg (pewnie kilka godzin roboty dla osoby która ściągnie projekt od zera)
2. Poczekać na to co będze z NET Core
3. Wrócić do tematu.

**Comment by kamil-mrzyglod** [comment]
Tak, tam trzeba to sprytnie ogarnąć - de facto da się zrobic tak, że masz max 1 logowanie na dzień(bo 24h to maksymalny czas życia tokena - ma to jednak swoje minusy jeśli chodzi o bezpieczeństwo). Auth0 dla tego typu projektów jest przyjemniejszy.

Tak wrzuciłem swoje 3 grosze - jak będę miał możliwość to pomogę bardziej doraźnie w postaci jakiegoś PR ;)

**Comment by pawlos** [comment]
@ptrstpp950 dodawać to logowanie via e-mail czy będziecie ogarniać Azure B2C lub Auth0?

**Comment by ptrstpp950** [comment]
Jak ogarniesz to będzie ekstra. Nim Azure b2c nadejdzie to jeszcze wieki miną. Na razie męczę się z migracja bazy
