### ISSUE TITLE
Migracja do nosql

### ISSUE THREAD

**Issue by ar-tour** [dotnetomaniak/dotnetomaniak#21]
Cześć,

czy rozważaliście migrację do bazy nosql?
Co sądzicie na ten temat?

**Comment by ptrstpp950** [comment]
Tak rozważałem. To co trzeba wsiąść pod uwagę to z mojego punktu widzenia:

- [ ] migrację starych danych
- [ ] koszty bazy NoSQL (przykładowo CosmosDB będzie kosztował DUŻO więcej niż aktualny SQL za 10EUR za miesiąc, ale Azure Table już pewnie dużo mniej)
- [ ] szybkość wykonywania zapytań
- [ ] możliwość skorzystania w Azure (czyli na przykład Cassandra czy ScyllaDB raczej odpadają)

Jeżeli chciałbyś przejrzeć kod, bazę i dać konkretną propozycję to ja jestem otwarty na propozycję.

**Comment by ar-tour** [comment]
A co powiesz na Mongo as a service?
https://www.mongodb.com/cloud/atlas/pricing

Tak poglądowo, dużo jest danych? Może zmieścimy się w wersji darmowej?

**Comment by ptrstpp950** [comment]
Zmieścisz się na oko w darmowej bo w tej chwili jest 400MB. Pytanie brzmi czy spełni ono wymagania wylistowane przeze mnie, ale bez wykonania jej pewnie nikt nie będzie wstanie odpowiedzieć.
Jest cała warstwa testów jednostkowych, które pewnie można by wykorzystać wydajnościowo i zobaczyć czy MongoDB daje radę.

Jeżeli nie planujesz na razie się tym zajmować to zamknę zgłoszenie. Jeżeli planujesz działać to zostawię je otwarte.

p.s. Ja raczej myślałem o lepszym cache niż migracji bazy. Bo w tej chwili nie da się zrobić cache inaczej niż wewnątrz aplikacji. Postaram się na dniach opisać co, jak i dlaczego. Może to rozjaśni obraz.

**Comment by ptrstpp950** [comment]
Wyślij mi na maila adres IP dostaniesz dostęp do bazy testowej.
Cały czas wydaje mi się że gra nie jest warta świeczki, ale jeżeli jesteś przekonany to może i mnie przekonasz wynikami.

p.s. W bazie będziesz miał dostęp do wszystki, więc obejrzysz sobie co i jak.

**Comment by kamil-mrzyglod** [comment]
A tak jaką wartość miałaby migracja do NoSQLa dla tego portalu? ;)
