### ISSUE TITLE
Logowanie

### ISSUE THREAD

**Issue by ar-tour** [dotnetomaniak/dotnetomaniak#22]
Aktualnie logi aplikacji są trzymane w plikach tekstowych (@ptrstpp950 nie mylę się? tak wywnioskowałem z web.configa).
W nowej wersji można zrobić to lepiej. Co powiesz na ELK stack?

Znalazłem 2 możliwości:
1. Instalacja ELKa na własną rękę na maszynie linuxowej:
https://logz.io/blog/install-elk-stack-azure/
2. ELK as a service. Darmowy plan przewiduje 3 dni retencji. Czy to wg Ciebie wystarczy?
https://logz.io/pricing/?utm_expid=.5jPN0ehWQva_hESJPCgb-g.0&utm_referrer=https%3A%2F%2Flogz.io%2Fproduct%2F

**Comment by ar-tour** [comment]
Aaa teraz już widzę, że używane jest Application Insights. Nigdy z tego nie korzystałem, myślałem, że to służy tylko do metryk.
Czyli zakładam, że wszystko będzie załatwione Application Insights?

**Comment by ptrstpp950** [comment]
Tak wszystko jest w application insights. Nawet az za dużo się zbiera i mi obciąza plan na 10 EUR miesięcznie i szukam sposobu na zmniejszenie ilości logowanych danych. 
Ale to temat na osobny błąd 😄
