### ISSUE TITLE
Zła czcionka na ekranie promocji

### ISSUE THREAD

**Issue by mszynka** [dotnetomaniak/dotnetomaniak#23]
W sekcji 'Materiały promocyjne' `https://dotnetomaniak.pl/PromoteSite` czcionka nie ma polskich znaków. To chyba jedyne miejsce, gdzie zauważyłem ten problem, ale warto pewnie sprawdzić czy może jeszcze wystąpić gdzieś indziej.

**Comment by pawlos** [comment]
@ptrstpp950 @mszynka coś musiał się przy migracji walnąć bo tam na 100% było prawidłowe kodowanie i polskie ogonki
