### ISSUE TITLE
Bug: Zła zależność na paczkę System.Configuration

### ISSUE THREAD

**Issue by mszynka** [dotnetomaniak/dotnetomaniak#25]
https://github.com/dotnetomaniak/dotnetomaniak/blob/d755fa5d9ecaf4d6cf55d5ecaf5937771d4a2734/v3.0/Source/Core/Kigg.Core.csproj#L98

Być może msbuild.exe nie widzi w tym problemu, ale na Linuxie taka niedokładność powoduje błędy builda.

**Comment by ptrstpp950** [comment]
Dziękuje

**Comment by ptrstpp950** [comment]
Jest już na produkcji: https://dev.azure.com/dotnetomaniak/dotnetomaniak/_releaseProgress?releaseId=6&_a=release-pipeline-progress

**Comment by mszynka** [comment]
To jest akurat taka zmiana, która działała tylko w środowisku Windowsa więc nikt niczego nie zauważy :smile:
