### ISSUE TITLE
(za)dużo wywołań StoryComment

### ISSUE THREAD

**Issue by ptrstpp950** [dotnetomaniak/dotnetomaniak#29]
W ciągu ostatnich 24 godzin zapytanie:
```
SELECT COUNT(*) AS [value] 
FROM [dbo].[StoryComment] AS [t0] 
INNER JOIN [dbo].[User] AS [t1] ON [t1].[Id] = [t0].[UserId]
WHERE [t0].[StoryId] = @p0
```
było wywołane:

_ | Request | Count
-- | -- | --
 1 | GET Feed/Tags | 19,286 |  
 2 | GET Feed/Category | 5,305 |  
 3 | GET Feed/Published | 2,125 |  
 4 | GET Feed/tags | 277 |  
 5 | GET Membership/Detail | 150 |  
 6 | GET Feed/Upcoming | 88 |  
 7 | POST Story/Publish | 1

Co jest tyle śmieszne że komentarze od dawna są facebookowe.

**Comment by ptrstpp950** [comment]
Najprawdopodbniej należy usunać/zmodyfikować poniższą linię:
https://github.com/dotnetomaniak/dotnetomaniak/blob/e667682c5eaf8de1eb517320e0cd356c4f3d1a56/v3.0/Source/Web/ActionResult/FeedResult.cs#L164

**Comment by GKotfis** [comment]
Wchodzę w to!
Tak na szybko co spojrzałem to usunięcie tej linijki spowoduje brak elementu 'commentCount' w generowanym RSS co może być problemem jeśli coś się do niego odwołuje. Jutro spojrzę głębiej w to :)

**Comment by GKotfis** [comment]
Tak więc nawet po dodaniu komentarza w RSS generowana jest wartość '0'. Więc nie wiem czy jest sens jej trzymania. Podejrzewam, że zamysł był taki aby użytkownik w czytniku widział, że ilość komentarzy uległa zmianie (lub w ogóle jakaś jest) i dzięki temu sprawdził artykuł.

**Comment by ptrstpp950** [comment]
@GKotfis ponieważ posiadałem tą wiedzę wcześniej (bo widziałem że komentarze sa z Facebook, a nie lokalnie) dlatego proponowałem usunięcie tej linii. Ale Twoja uwaga jest słuszna więc można na razie wstawić zero.

**Comment by ptrstpp950** [comment]
Jest lepiej ale nadal mam 468 wywołań w ciągu ostaniej godziny na operacji: GET Feed/Tags
Wczoraj o tej samej porze było 868 :)

**Comment by ptrstpp950** [comment]
Chyba trzeba usunąć u źródła a nie wykorzystanie.

**Comment by GKotfis** [comment]
Przeoczyłem jeszcze jedno miejsce w Feed, które wykorzystuje CommentCount więc zrobiłem dodatkową zmianę #33 
Całkowite usunięcie masz na myśli z modelu domenowego `IStory.CommentCount`?

**Comment by ptrstpp950** [comment]
Tak myślałem. Na razie jest dużo lepiej, więc działa dziękuję. 

Może przy okazji mogracji do EF Core (albo co tam bedzie) usuniemy.
