### ISSUE TITLE
Usunąć komponent Google+

### ISSUE THREAD

**Issue by GKotfis** [dotnetomaniak/dotnetomaniak#31]
W związku z zapowiedzią [wyłączenia serwisu Google+](https://blog.google/technology/safety-security/project-strobe/) nie ma sensu linkowania do niego.
Do zmiany:
1. Usunięcie widgetu 'Google+ z prawej sekcji strony
2.  Usunięcie małej ikony 'G+' z sekcji 'Wszystkie'

**Comment by ptrstpp950** [comment]
Wdrożone, dziękuję
