### ISSUE TITLE
Poprawa stylu przycisku logowania przez Facebook 

### ISSUE THREAD

**Issue by WTobor** [dotnetomaniak/dotnetomaniak#53]
![image](https://user-images.githubusercontent.com/22730914/49699449-9c129400-fbd1-11e8-9c18-b9067b74a01f.png)
Przy długim imieniu użytkownika napis "Kontynuuj jako $imię" nie mieści się na przycisku

**Comment by pawlos** [comment]
@WTobor sprawdzisz czy naprawione? Ja mam niestety, krótkie imię ;)

**Comment by WTobor** [comment]
@pawlos  działa elegancko :)

**Comment by pawlos** [comment]
@WTobor, @ptrstpp950 no to zamykamy!
