### ISSUE TITLE
Dodanie nowego artykułu nie generuje miniaturki

### ISSUE THREAD

**Issue by danielplawgo** [dotnetomaniak/dotnetomaniak#6]
Nie zawsze (a patrząc po większości wpisach) wygrywają się miniaturki podczas dodawania wpisu. Jak byłoby jak by można było dodać taką miniaturkę samemu.

![dotnetomianiak](https://user-images.githubusercontent.com/70243/45530120-63893700-b7e9-11e8-81e9-1b2e11ca4a63.png)

**Comment by ptrstpp950** [comment]
Mówiąc szczerze to z tymi minaturkami jest babol. W widoku admina jest przycisk miniaturka i wtedy się pobiera bez problemu (co właśnie uczyniłem na Twoim wpisie). Ale nie wiem dlaczego ten kod nie wywołuje się sam. Inna kwestia to gdzie trzymać te miniatury. 

Uwaga tak czy siak słuszna. Jedynie zastanawiam się czy rozbić to zgłoszenie na 2:
- naprawa pobierania miniatur
- dodawanie własnych miniatur

czy zostawić jedno

**Comment by danielplawgo** [comment]
Faktycznie chyba lepiej rozbić to dwa oddzielne zgłoszenia, szczególnie, że poprawienie generowania będzie dużo łatwiejsze niż dodanie własnej miniaturki.

**Comment by pawlos** [comment]
Zrób oddzielne - miniatury na pewno pobierają się same, choć nie zawsze dzieje się to real-time to może na to uda mi się zerknąć. 

W ogóle to warto rozważyć przejście na darmowy silnik, bo ten który jest używany jest płatny (choć nie są to jakieś astronomiczne kwoty).

**Comment by pawlos** [comment]
@ptrstpp950 możesz mnie do tego przypisać to nie zapomnę na to zerknąć

**Comment by ptrstpp950** [comment]
zrobione

**Comment by pawlos** [comment]
@ptrstpp950 widzę kredyty są. Możesz mi podesłać więc powinny się generować. Możesz mi na priv podesłać obecne ustawienia browshot w web.config?

**Comment by pawlos** [comment]
ok. Stad problem z generowaniem się miniatur

**Comment by pawlos** [comment]
@ptrstpp950 robimy coś z tym?

**Comment by ptrstpp950** [comment]
@pawlos jak będę miał wolny wieczór to przeniosę konfigurację do app settings bo inaczej Azure ma z nią problem.

**Comment by ptrstpp950** [comment]
Naprawaione i wdrożone na produkcje
