### ISSUE TITLE
Błąd przy zakładaniu konta

### ISSUE THREAD

**Issue by ptrstpp950** [dotnetomaniak/dotnetomaniak#9]
Jeżeli nastąpi następująca sytuacja:

- Użytkownik założy konto
- Użytkownik z jakiegoś powodu nie dokona jego potwierdzenia (zapomni, nie dojdzie email, etc.)

To dane konto jest "stracone". Nie da się go potwierdzić (informacja o tym, że konto już istnieje), ani na nie zalogować (konto nie jest aktywne).

**Comment by DawidJanocha** [comment]
> Nie da się go potwierdzić (informacja o tym, że konto już istnieje), ani na nie zalogować (konto nie jest aktywne).
W jaki sposób próbujesz potwierdzić? Czy masz na myśli próbę ponownej rejestracji na ten sam adres e-mail?

**Comment by ptrstpp950** [comment]
Rzeczywiscie nie opisałem wystarczająco czytelnie. Kiedy mamy takie konto to:

- nie da się zarejstrować na nie, bo pisze że już istnieje
- nie da się ponownie wysłać maila z potwierdzeniem, bo nie ma takiego przycisku
- nie da się na nie zalogować, bo nie jest aktywne

**Comment by pawlos** [comment]
Zwykle takie przypadki (bardzo sporadyczne) ogarniałem odpowiednią zmianą pola w bazie, ale faktycznie może przycisk wysyłający maila z potwierdzeniem byłby jakimś rozwiązaniem.
